import Head from "next/head";

// components
import CursorProvider from "@components/cursor/CursorContext";
import MainHeader from "src/layouts/main/MainHeader";
import { PitStudio } from "pages/_app";
import SectionFooter from "../home/components/SectionFooter";
import SectionCover from "./components/SectionCover";
import SectionDetail from "./components/SectionDetail";

import LoadingOverlay from "@components/loading/LoadingOverlay";
import SectionBenefit from "./components/SectionBenefit";

export default function ServicesPage() {
  return (
    <CursorProvider>
      {/* <DebuggerFrontEnd /> */}
      <Head>
        <title>Pit Studio - Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <style jsx global>
        {`
          /* Hide scrollbar for Chrome, Safari and Opera */
          ::-webkit-scrollbar,
          #main::-webkit-scrollbar {
            display: none;
          }

          /* Hide scrollbar for IE, Edge and Firefox */
          * {
            -ms-overflow-style: none; /* IE and Edge */
            scrollbar-width: none; /* Firefox */
          }
        `}
      </style>
      <LoadingOverlay />
      <main id="main" className={PitStudio.className}>
        <MainHeader animationDisable />
        <SectionCover />
        <SectionDetail />
        <SectionBenefit />
        {/* <SectionCover tabs={["ALL CASES", "MOBILE APPS", "WEBSITES", "PRODUCTS"]} />
        <SectionListProjects /> */}
        <SectionFooter />
      </main>
    </CursorProvider>
  );
}
